<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log InRegister As Student</name>
   <tag></tag>
   <elementGuidId>84a7a82d-9eff-41f6-90ce-ebf1e7828d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3702']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3702 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>202f68d4-8bc5-4538-bc72-6ceefa083e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testautomasi.com/profile</value>
      <webElementGuid>a22e97ec-14ef-465c-998b-a62295be2df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In/Register As Student</value>
      <webElementGuid>82e9e222-8347-4dec-87df-da5a8a755658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3702&quot;)/a[1]</value>
      <webElementGuid>4a19b6fb-6069-460f-b706-8fffe5e872c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3702']/a</value>
      <webElementGuid>c8d869c9-13f9-4610-9a39-6b9ea94551e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In/Register As Student')]</value>
      <webElementGuid>6ba63d1f-7b61-421a-9d14-59971d120133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://testautomasi.com/profile')])[2]</value>
      <webElementGuid>63de5c43-3bec-4458-b4f9-2b3872b35b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>87ea5d47-8b14-4fb3-8219-089e1b552c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testautomasi.com/profile' and (text() = 'Log In/Register As Student' or . = 'Log In/Register As Student')]</value>
      <webElementGuid>f8fdf9d3-8ccc-4ccd-97dc-a9269133baf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
