<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Profile</name>
   <tag></tag>
   <elementGuidId>4d950de0-fb81-4bf4-b1b9-03bd4ba2063a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.current</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5202d089-6a74-4e73-b755-f49f3f690cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>dae026de-3309-490d-971b-a01fb94e22ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>cae2864b-45d0-4003-8647-a88085b43094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crumbs&quot;)/span[@class=&quot;current&quot;]</value>
      <webElementGuid>b7888638-0aa0-4383-b7c3-7488f7d98b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='crumbs']/span</value>
      <webElementGuid>0717ed56-fbfb-4c31-a434-87f346a7a440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>71069281-d352-4ae4-b8fe-cec15ca45fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>a7698480-dca3-4074-a10d-e3d9e21230ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
