<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_E-Learning</name>
   <tag></tag>
   <elementGuidId>c970659a-a903-43ff-93f6-51ee81a3d769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNav']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04bf4e33-9782-467f-b60d-ede308d77d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link page-scroll</value>
      <webElementGuid>649031bc-3567-4a5f-9e6a-e92b9424dd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ba7a1e4f-8ca0-4d6d-b858-f65d08c0e54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testautomasi.com/course/</value>
      <webElementGuid>2fe411aa-ed3f-48b9-bf89-391a2dbf4c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Learning</value>
      <webElementGuid>7f154df0-0e08-4377-9f9b-7a76c5658d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNav&quot;)/ul[@class=&quot;navbar-nav ml-md-auto typo-color-c align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link page-scroll&quot;]</value>
      <webElementGuid>44224250-58f1-41ea-aba8-d4fc3384dd8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNav']/ul/li[5]/a</value>
      <webElementGuid>12cd3458-e077-4159-b502-0ec4d603d684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'E-Learning')]</value>
      <webElementGuid>012ce96c-b905-403a-9a67-96f4b7e0dd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testautomasi.com/course/')]</value>
      <webElementGuid>b31c85bf-28aa-4ce3-a816-c4365d18a5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>47f2a4c0-c129-4e38-8eb6-6eed52bd724d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testautomasi.com/course/' and (text() = 'E-Learning' or . = 'E-Learning')]</value>
      <webElementGuid>f4bea785-015b-41d1-b21f-ddc7ff97090c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
